variables:
- group: GitHubAccess

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  inputs:
    script: |
      git submodule update

- task: HugoTask@1
  inputs:
    source: 'src'
    destination: '$(System.DefaultWorkingDirectory)\docs\'
    baseURL: 'http://thomasmporter.github.io/'

- task: GitHubPagesPublish@1
  inputs:
    docPath: '$(System.DefaultWorkingDirectory)\docs\*'
    githubusername: 'ThomasMPorter'
    githubemail: 'thomasmporterii@gmail.com'
    githubaccesstoken: $(gitHubToken)
    repositoryname: 'ThomasMPorter.github.io'
    branchname: 'master'
    commitmessage: 'Automated Release'
