trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- checkout: self
  submodules: true

- task: HugoTask@1
  inputs:
    source: 'src'
    destination: '$(Build.ArtifactStagingDirectory)'
    baseURL: 'http://thomasmporter.github.io/'

- task: GitHubPagesPublish@1
  inputs:
    docPath: '$(Build.ArtifactStagingDirectory)/a/'
    githubusername: 'ThomasMPorter'
    githubemail: 'thomasmporterii@gmail.com'
    githubaccesstoken: '828f6b6b7bcb9ef96c7eed150aeed98810341db9'
    repositoryname: 'ThomasMPorter.github.io'
    branchname: 'master'
    commitmessage: 'Automated Release $(Release.ReleaseId)'
