name: Render and Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Powerful Hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        source: 'src'
        target: 'docs'
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        repo: 'ThomasMPorter/ThomasMPorter.github.io'
        target_branch: 'master'
        build_dir: 'docs'
env:
  GITHUB_TOKEN: ${{ secrets.BlogToken }}
